export const BRAND_COLORS = {
  sunset: '#F6BD60',
  linen: '#F7EDE2',
  blush: '#F5CAC3',
  sage: '#84A59D',
  coral: '#F28482',
  ink: '#23312D',
  darkSage: '#2F4F49',
} as const;

export const ECOLOGUE_ASSETS = {
  // SVG originaux
  icon: '/brand/ecologue-logo-icon.svg',
  text: '/brand/ecologue-logo-text.svg',
  full: '/brand/ecologue-logo-full.svg',
  textLightBg: '/brand/ecologue-text-light-bg.svg',
  textDarkBg: '/brand/ecologue-text-dark-bg.svg',
  textMonoYellow: '/brand/ecologue-text-mono-yellow.svg',
  textMonoPink: '/brand/ecologue-text-mono-pink.svg',
  textMonoGreen: '/brand/ecologue-text-mono-green.svg',
  iconLightBg: '/brand/ecologue-icon-light-bg.svg',
  iconDarkBg: '/brand/ecologue-icon-dark-bg.svg',
  iconMonoYellow: '/brand/ecologue-icon-mono-yellow.svg',
  iconMonoPink: '/brand/ecologue-icon-mono-pink.svg',
  iconMonoGreen: '/brand/ecologue-icon-mono-green.svg',
  fullLightBg: '/brand/ecologue-full-light-bg.svg',
  fullDarkBg: '/brand/ecologue-full-dark-bg.svg',
  fullMonoYellow: '/brand/ecologue-full-mono-yellow.svg',
  fullMonoPink: '/brand/ecologue-full-mono-pink.svg',
  fullMonoGreen: '/brand/ecologue-full-mono-green.svg',
  // PNG optimisé et rogné pour un affichage fiable dans l’en-tête, la home et le footer
  fullPng: '/brand-png/ecologue-logo-full.png',
} as const;

export const SITE_CONFIG = {
  appName: 'ecologue.app',
  ownerName: 'Agathe Maussion',
  companyName: 'Nonoké',
  companyBaseline: 'Ingénierie écologique, biodiversité & habitat écologique',
  websiteUrl: 'https://www.nonoke.fr',
  appointmentUrl: 'https://zcal.co/agathemaussion/contact',
  linkedinUrl: 'https://www.linkedin.com/in/agathe-maussion/',
  contactEmail: 'agathe.maussion@gmail.com',
  contactPhone: '06 84 68 20 95',
  legalName: 'Agathe Maussion',
  legalStatus: 'Micro-entreprise',
  siret: '929 694 149 00014',
  professionalAddress: '540 chemin du Boullidou, 13510 Éguilles',
  hostName: 'OVHcloud',
  hostLegalName: 'OVH SAS',
  hostAddress: '2 rue Kellermann, 59100 Roubaix, France',
  privacyUrl: '/confidentialite',
  legalUrl: '/mentions-legales',
  dataCollectionMode: 'supabase-voluntary',
  nonokeLogoUrl: '/logo-nonoke.png',
  logoUrl: '/logo-nonoke.png',
  ecologueLogoUrl: ECOLOGUE_ASSETS.fullPng,
  ecologueIconUrl: ECOLOGUE_ASSETS.icon,
  colors: BRAND_COLORS,
  assets: ECOLOGUE_ASSETS,
} as const;
